### ISSUE TITLE
event bus signals cause threading error

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#14]

**Comment by marisademeglio** [comment]
This seems to happen for messages, not statuses (as previously thought), and not even for every message. The error output is:

DEBUG [   o.d.p.p.impl.job.PersistentJobContext] Post loading jobcontext   @o.d.p.p.i.job.PersistentJobContext:119#postLoad
Exception in thread "Thread-39" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-39
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:204)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:438)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:364)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204)
	at com.sun.javafx.scene.control.skin.ListCellSkin.handleControlPropertyChanged(ListCellSkin.java:49)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$$Lambda$225/1533792833.call(Unknown Source)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.scene.control.Labeled.setText(Labeled.java:145)
	at com.sun.javafx.scene.control.skin.ListViewSkin$2.updateItem(ListViewSkin.java:294)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
	at javafx.scene.control.ListCell.lambda$new$163(ListCell.java:167)
	at javafx.scene.control.ListCell$$Lambda$330/67368892.onChanged(Unknown Source)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.daisy.pipeline.gui.databridge.ObservableJob.addMessage(ObservableJob.java:42)
	at org.daisy.pipeline.gui.databridge.DataManager.addMessage(DataManager.java:38)
	at org.daisy.pipeline.gui.databridge.EventBusListener.handleMessage(EventBusListener.java:29)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at org.daisy.common.xproc.calabash.impl.EventBusMessageListener.post(EventBusMessageListener.java:44)
	at org.daisy.common.xproc.calabash.impl.EventBusMessageListener.info(EventBusMessageListener.java:135)
	at org.daisy.common.xproc.calabash.impl.XProcMessageListenerAggregator.info(XProcMessageListenerAggregator.java:103)
	at com.xmlcalabash.core.XProcRuntime.info(Unknown Source)
	at com.xmlcalabash.library.DefaultStep.info(Unknown Source)
	at org.daisy.common.xproc.calabash.steps.Message$MessageStep.run(Message.java:36)
	at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source)
	at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source)
	at com.xmlcalabash.runtime.XChoose.run(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
	at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source)
	at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242)
	at org.daisy.pipeline.job.Job.run(Job.java:216)
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:110)
	at java.lang.Thread.run(Thread.java:745)

**Comment by marisademeglio** [comment]
This is now noticeable for statuses too, and it affects any subscribers to the job status property (sidebar table, menu items, job details pane)

**Comment by marisademeglio** [comment]
Adding runLater to the details pane seems to work for displaying results links when the job is done. However, wrapping menu item updates in runLater somehow disables the sidebar from accurately reflecting the job status. They aren't linked in any way, so perhaps it's just a thread issue.

**Comment by capitancambio** [comment]
Do you need to tell javafx to repaint the sidebar once the value has been
updated? playing by ear here, so it might not be the issue.

cheers,

Javi

**Comment by marisademeglio** [comment]
@capitancambio no I don't think that's the issue - all the table cells in the sidebar are bound to the values in the data layer (which gets updated via the event bus). it works sometimes; I don't think there's a direct link with runLater. I want to see how it behaves on other machines.

**Comment by bertfrees** [comment]
I believe I have fixed this in the latest version. See e751564c82a1660c1534c3ef77bf123d40da2685.
