### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-gui#34]
reported on linux. check other platforms.

**Comment by marisademeglio** [comment]
they work on OSX. need to know the right file browser launch command on linux.

**Comment by josteinaj** [comment]
I've been using `gnome-open` but it seems that `xdg-open` is the thing to use nowadays since `gnome-open` is not installed by default.

`xdg-open "http://www.google.com"` works for me.

**Comment by marisademeglio** [comment]
@josteinaj I've added this; would you mind having a look when you get a chance to see if it works? the "read documentation online" links use a different mechanism than the results links, so if you could check both, that would be great.

**Comment by josteinaj** [comment]
Clicking "Read online documentation" gives this exception:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at javafx.application.HostServices.showDocument(HostServices.java:127)
    at org.daisy.pipeline.gui.ScriptInfoHeaderVBox$1.handle(ScriptInfoHeaderVBox.java:36)
    at org.daisy.pipeline.gui.ScriptInfoHeaderVBox$1.handle(ScriptInfoHeaderVBox.java:34)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Node.fireEvent(Node.java:8390)
    at javafx.scene.control.Hyperlink.fire(Hyperlink.java:153)
    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3758)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$324/654117069.get(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:927)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$43/834212397.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
```


The following exception is what I get when I try to open the log file. Maybe you forgot adding `xdg-open` before the file URL or something?

```
java.io.IOException: Cannot run program "file:/home/jostein/daisy-pipeline/pipeline-assembly/target/pipeline2-1.9_linux/daisy-pipeline/data/jobs/5c1146aa-84c2-4e18-ae12-d8667191cb45/5c1146aa-84c2-4e18-ae12-d8667191cb45.log": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:347)
    at org.daisy.pipeline.gui.GridPaneHelper$1.handle(GridPaneHelper.java:95)
    at org.daisy.pipeline.gui.GridPaneHelper$1.handle(GridPaneHelper.java:91)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Node.fireEvent(Node.java:8390)
    at javafx.scene.control.Hyperlink.fire(Hyperlink.java:153)
    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3758)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$324/654117069.get(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:927)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$43/834212397.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 62 more
```

**Comment by marisademeglio** [comment]
Ok, I've changed it so only the scripts with links in the xproc get a link entry in the GUI. I didn't realize that some of them didn't specify documentation. I don't know if this was the problem or not. Also, if the host services that javafx uses to launch browsers fails, there should be an error in the output now.

And for the file links, can you try again? Every time you click one, you should see output of what the command was. E.g. 

```$$$$$$$$$$$$ GUI link clicked: open file:/Users/marisa/Projects/pipeline2/pipeline-assembly/target/pipeline2-1.9_mac/daisy-pipeline/data/jobs/36d3680f-fbef-43fc-a3d0-e17e9a6c6855/output/validation-status/validation-status.xml```

**Comment by josteinaj** [comment]
Now only some of the scripts have the "Read onlinne documentation" link. It still throws the NullPointerException though. No other output.

I'm still getting the IOException when trying to open files from the result. In addition, these kinds of messages before the exception:
```
$$$$$$$$$$$$ GUI link clicked:  file:/home/jostein/daisy-pipeline/pipeline-assembly/target/pipeline2-1.9_linux/daisy-pipeline/data/jobs/3d59b4a9-1b7b-4dec-8029-b1f62c6bf50e/3d59b4a9-1b7b-4dec-8029-b1f62c6bf50e.log
$$$$$$$$$$$$ GUI link clicked:  file:/home/jostein/daisy-pipeline/pipeline-assembly/target/pipeline2-1.9_linux/daisy-pipeline/data/jobs/3d59b4a9-1b7b-4dec-8029-b1f62c6bf50e/output/validation-status/validation-status.xml
$$$$$$$$$$$$ GUI link clicked:  file:/tmp/out/dtbook-validation-report.xhtml
```

Also, I'm getting this exception for each new message while running a job it seems:
```
INFO  [     o.d.c.x.c.steps.Message$MessageStep] bundle://54.0:1/xml/xproc/message.xpl:116:29:Storing reports to disk in output directory: file:/tmp/out/   @o.d.c.x.c.i.slf4jXProcMessageListener:80#info
DEBUG [ org.eclipse.persistence.logging.default] Connection(729972351)--Thread(Thread[Thread-25,5,Configuration Admin Service])--SELECT job_id, PRIORITY, STATUS, CONTEXT_job_id FROM jobs WHERE (job_id = ?)
	bind => [1 parameter bound]   @o.d.p.p.logging.Slf4jSessionLogger:108#log
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=DTBook Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] load script XProcScript[name=DTBook Validator]   @o.d.p.p.i.job.PersistentJobContext:207#setScriptUri
DEBUG [   o.d.p.p.impl.job.PersistentJobContext] Post loading jobcontext   @o.d.p.p.i.job.PersistentJobContext:119#postLoad
Exception in thread "Thread-25" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-25
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:204)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:438)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:364)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204)
	at com.sun.javafx.scene.control.skin.ListCellSkin.handleControlPropertyChanged(ListCellSkin.java:49)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$$Lambda$237/673032039.call(Unknown Source)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.scene.control.Labeled.setText(Labeled.java:145)
	at com.sun.javafx.scene.control.skin.ListViewSkin$2.updateItem(ListViewSkin.java:294)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
	at javafx.scene.control.ListCell.lambda$new$163(ListCell.java:167)
	at javafx.scene.control.ListCell$$Lambda$361/2118101062.onChanged(Unknown Source)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.daisy.pipeline.gui.databridge.ObservableJob.addMessage(ObservableJob.java:42)
	at org.daisy.pipeline.gui.databridge.DataManager.addMessage(DataManager.java:38)
	at org.daisy.pipeline.gui.databridge.EventBusListener.handleMessage(EventBusListener.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at org.daisy.common.xproc.calabash.impl.EventBusMessageListener.post(EventBusMessageListener.java:44)
	at org.daisy.common.xproc.calabash.impl.EventBusMessageListener.info(EventBusMessageListener.java:135)
	at org.daisy.common.xproc.calabash.impl.XProcMessageListenerAggregator.info(XProcMessageListenerAggregator.java:103)
	at com.xmlcalabash.core.XProcRuntime.info(Unknown Source)
	at com.xmlcalabash.library.DefaultStep.info(Unknown Source)
	at org.daisy.common.xproc.calabash.steps.Message$MessageStep.run(Message.java:36)
	at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source)
	at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source)
	at com.xmlcalabash.runtime.XChoose.run(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
	at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source)
	at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source)
	at com.xmlcalabash.runtime.XChoose.run(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
	at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source)
	at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source)
	at com.xmlcalabash.runtime.XChoose.run(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
	at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242)
	at org.daisy.pipeline.job.Job.run(Job.java:216)
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:110)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by josteinaj** [comment]
Fro the results links issue; could it be a problem with getFileBrowserCommand in PlatformUtils.java returning the empty string?

[This page](http://www.mkyong.com/java/how-to-detect-os-in-java-systemgetpropertyosname/) suggests detecting Linux/Unix with:

```java
return (OS.indexOf("nix") >= 0 || OS.indexOf("nux") >= 0 || OS.indexOf("aix") > 0 );
```

**Comment by josteinaj** [comment]
...yeah my "os.name" system property reads "Linux":

```java
class Test {
    public static void main(String args[]) {
        System.out.println(System.getProperty("os.name"));
    }
}
```

```
➜  /tmp  javac Test.java && java Test
Linux
```

**Comment by marisademeglio** [comment]
@josteinaj , related to the thread error output, do you see the status change in real time? for me, that error used to show up but doesn't anymore (though i didn't change anything), and it was related to binding javafx gui widgets to status changes coming from the pipeline thread. but if the changes are being made in real time, then maybe this error is more of a warning.

**Comment by marisademeglio** [comment]
the web links should work better in linux now (it uses the xdg-open command instead of javafx HostServices)

**Comment by josteinaj** [comment]
*web links*: work great (except that I can't get it working with chromium, I'll have to look into that).

*error output*: The status changes in real time, I don't need to refresh or anything.
